version: 0.2

phases:
  build:
    commands:
      - echo entered the build phase
      - gradle clean build
  install:
    runtime-versions:
      java: corretto8
      
  post build:
    commands:
      - echo Build completed successfully
      
artifacts:
  files: 
    - build/libs/spring-boot-gradle-0.0.1-snapshot.jar
  discard-paths: yes